# Has been de-licensed

body:
# atom
  - repo:
            "atom"
    fork:
            "n"
    license:
            "GPLv3"
    readme:
            "y"
    maintained:
            "n"
    working:
            "y"
    description:
            "Configuration files for Atom, specifically the configuration files found in my ~/.atom directory."

# emacs
  - repo:
            "emacs"
    category:
            "configuration"
    fork:
            "n"
    license:
            "GPLv3"
    readme:
            "y"
    maintained:
            "n"
    working:
            "y"
    description:
            "My emacs configuration settings (stored in `~/.emacs`). Has a quick install script too."

# funtoo-config
  - repo:
            "funtoo-config"
    category:
            "configuration"
    fork:
            "n"
    license:
            "GPLv3"
    readme:
            "y"
    maintained:
            "y"
    working:
            "y"
    description:
            "My Funtoo configuration settings."

# gentoo-config
  - repo:
            "gentoo-config"
    category:
            "configuration"
    fork:
            "n"
    license:
            "GPLv3"
    readme:
            "y"
    maintained:
            "y"
    working:
            "y"
    description:
            "My Gentoo configuration settings."

# i3-configs
  - repo:
            "i3-configs"
    category:
            "configuration"
    fork:
            "n"
    license:
            "GPLv3"
    readme:
            "y"
    maintained:
            "y"
    working:
            "y"
    description:
            "My i3 configuration settings. Written in C++, Python and Shell."

# spacemacs
  - repo:
            "spacemacs"
    fork:
            "n"
    license:
            "GPLv3"
    readme:
            "n"
    maintained:
            "n"
    working:
            "y"
    description:
            "My `~/.spacemacs` file."

# vim
  - repo:
            "vim"
    fork:
            "n"
    license:
            "GPLv3"
    readme:
            "n"
    maintained:
            "y"
    working:
            "y"
    description:
            "My `~/.vimrc` file."
